# Remote theme directory
remote_theme: analytics-link/analytics-link.github.io

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme

#-------------------------------
# General Site Settings
title: Emmanuel Kanati
description: "Hi, I'm Emmanuel, a Data Science and Business Intelligence Professional. I leverage tools like Python, SQL, Excel, Tableau, and Power BI to analyse large datasets and create impactful visualisations and reports. My expertise spans various machine learning techniques, including supervised and unsupervised learning, enabling me to extract valuable insights from complex data.

With strong project management skills, I excel in managing projects and effectively communicating findings to stakeholders, driving informed decision-making. Explore my Data Science portfolio to see projects focused on delivering significant business impact. Connect with me on LinkedIn!"
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

#-------------------------------
# About Section
subtitle: Data Science <span style="color:#f58506"> Portfolio </span>
location: "UK"

avatar_image: "/img/Profilepic.jpg" 
#-------------------------------
# Contact links
linkedln: "https://www.linkedin.com/in/emmanuel-mawuli-kanati-41a59156/"
github: "https://github.com/ekanati"  

paginate: 6
paginate_path: "/page/:num"

sass:
  sass_dir: _sass
  style: compressed # possible values: nested expanded compact compressed

defaults:
  - scope:
      type: posts
    values:
      layout: post
      read_time: true
      share: false


#-------------------------------
# Exclude from processing.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

